#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_Reworked
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PrototypeDB")]
	public partial class SiteFunctionsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAppointment(Appointment instance);
    partial void UpdateAppointment(Appointment instance);
    partial void DeleteAppointment(Appointment instance);
    #endregion
		
		public SiteFunctionsDataContext() : 
				base(global::Prototype_Reworked.Properties.Settings.Default.PrototypeDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SiteFunctionsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SiteFunctionsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SiteFunctionsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SiteFunctionsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Appointment> Appointments
		{
			get
			{
				return this.GetTable<Appointment>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertAppointment")]
		public int InsertAppointment([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string appointmentTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string appointmentDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> appointmentDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string appointmentTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientID", DbType="Int")] System.Nullable<int> patientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), appointmentTitle, appointmentDescription, appointmentDate, appointmentTime, patientID);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Appointment")]
	public partial class Appointment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _appID;
		
		private string _appointmentTitle;
		
		private string _appointmentDescription;
		
		private System.Nullable<System.DateTime> _appointmentDate;
		
		private string _appointmentTime;
		
		private string _Status;
		
		private string _Created;
		
		private System.Nullable<bool> _attendance;
		
		private System.Nullable<int> _PatientID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnappIDChanging(int value);
    partial void OnappIDChanged();
    partial void OnappointmentTitleChanging(string value);
    partial void OnappointmentTitleChanged();
    partial void OnappointmentDescriptionChanging(string value);
    partial void OnappointmentDescriptionChanged();
    partial void OnappointmentDateChanging(System.Nullable<System.DateTime> value);
    partial void OnappointmentDateChanged();
    partial void OnappointmentTimeChanging(string value);
    partial void OnappointmentTimeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreatedChanging(string value);
    partial void OnCreatedChanged();
    partial void OnattendanceChanging(System.Nullable<bool> value);
    partial void OnattendanceChanged();
    partial void OnPatientIDChanging(System.Nullable<int> value);
    partial void OnPatientIDChanged();
    #endregion
		
		public Appointment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int appID
		{
			get
			{
				return this._appID;
			}
			set
			{
				if ((this._appID != value))
				{
					this.OnappIDChanging(value);
					this.SendPropertyChanging();
					this._appID = value;
					this.SendPropertyChanged("appID");
					this.OnappIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointmentTitle", DbType="NChar(50)")]
		public string appointmentTitle
		{
			get
			{
				return this._appointmentTitle;
			}
			set
			{
				if ((this._appointmentTitle != value))
				{
					this.OnappointmentTitleChanging(value);
					this.SendPropertyChanging();
					this._appointmentTitle = value;
					this.SendPropertyChanged("appointmentTitle");
					this.OnappointmentTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointmentDescription", DbType="NVarChar(MAX)")]
		public string appointmentDescription
		{
			get
			{
				return this._appointmentDescription;
			}
			set
			{
				if ((this._appointmentDescription != value))
				{
					this.OnappointmentDescriptionChanging(value);
					this.SendPropertyChanging();
					this._appointmentDescription = value;
					this.SendPropertyChanged("appointmentDescription");
					this.OnappointmentDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointmentDate", DbType="Date")]
		public System.Nullable<System.DateTime> appointmentDate
		{
			get
			{
				return this._appointmentDate;
			}
			set
			{
				if ((this._appointmentDate != value))
				{
					this.OnappointmentDateChanging(value);
					this.SendPropertyChanging();
					this._appointmentDate = value;
					this.SendPropertyChanged("appointmentDate");
					this.OnappointmentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appointmentTime", DbType="NVarChar(10)")]
		public string appointmentTime
		{
			get
			{
				return this._appointmentTime;
			}
			set
			{
				if ((this._appointmentTime != value))
				{
					this.OnappointmentTimeChanging(value);
					this.SendPropertyChanging();
					this._appointmentTime = value;
					this.SendPropertyChanged("appointmentTime");
					this.OnappointmentTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="NVarChar(50)")]
		public string Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attendance", DbType="Bit")]
		public System.Nullable<bool> attendance
		{
			get
			{
				return this._attendance;
			}
			set
			{
				if ((this._attendance != value))
				{
					this.OnattendanceChanging(value);
					this.SendPropertyChanging();
					this._attendance = value;
					this.SendPropertyChanged("attendance");
					this.OnattendanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int")]
		public System.Nullable<int> PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this.OnPatientIDChanging(value);
					this.SendPropertyChanging();
					this._PatientID = value;
					this.SendPropertyChanged("PatientID");
					this.OnPatientIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
